%%
%% Generated by jerg v1.0 on 2013-04-22 at 10:22:41
%%
%% DO NOT EDIT - CHANGES WILL BE OVERWRITTEN!
%%

% Monetary price
% Intended to be used embedded in other schemas
-record(pre_price,
        {
            currency_code :: binary(),
            amount        :: number()
        }).

% Product (Short View)
% Intended to be used in search results
-record(pre_product_short,
        {
            % Numeric object identity, set to -1 at creation time
            id             = -1 :: integer(),
            name                :: binary(),
            list_price          :: #pre_pre_price{},
            discount_price      :: #pre_pre_price{}
        }).

% Product Category
-record(pre_product_category,
        {
            % Numeric object identity, set to -1 at creation time
            id   = -1 :: integer(),
            name      :: binary()
        }).

% Product (Full View)
% Intended to be used when full description is needed
-record(pre_product_full,
        {
            % Numeric object identity, set to -1 at creation time
            id             = -1 :: integer(),
            name                :: binary(),
            list_price          :: #pre_pre_price{},
            discount_price      :: #pre_pre_price{},
            description         :: binary(),
            categories          :: list(#pre_product_category{})
        }).

