%%
%% Generated by jerg v1.0
%%
%% DO NOT EDIT - CHANGES WILL BE OVERWRITTEN!
%%

-record(types_showcase,
        {
            booleanProperty       :: boolean(),
            stringProperty        :: binary(),
            integerProperty       :: integer(),
            numberProperty        :: number(),
            arrayProperty         :: list(term()),
            nullProperty          :: null,
            anyProperty           :: any(),
            objectProperty        :: term(),
            defaultProperty       :: term(),
            unknownProperty       :: some_unknown_type(),
            primitiveErlangType   :: file:io_device(),
            string_enum_Property  :: binary(),
            integer_enum_Property :: 1 | 2 | null,
            number_enum_Property  :: number(),
            boolean_enum_Property :: boolean()
        }).

